### ISSUE TITLE
Stuck at loading

### ISSUE THREAD

**Issue by tajulasri** [ayoubamine/flutter_tawk#1]
Hi,

I've tried using this library to my flutter project somehow its stuck on "loading" placeholder without load chat window. Direct link fine cause i tried to open via browser is worked.

my Flutter SDK version
```
[✓] Flutter (Channel stable, 1.22.3, on Mac OS X 10.15.7 19H2, locale en-MY) 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[✓] Android Studio (version 3.5)
[✓] IntelliJ IDEA Community Edition (version 2020.2.3)
[✓] VS Code (version 1.51.1)
[✓] Connected device (2 available)
```

![Simulator Screen Shot - iPhone 12 Pro Max - 2020-11-28 at 02 16 20](https://user-images.githubusercontent.com/6530495/100476200-f212d600-311f-11eb-92b5-2f320b415c17.png)

**Comment by zhuhean** [comment]
//          navigationDelegate: (NavigationRequest request) {
//            if (widget.onLinkTap != null) {
//              widget.onLinkTap(request.url);
//            }
//            return NavigationDecision.prevent;
//          },

For me, remove these lines helped.

**Comment by ayoubamine** [comment]
Thanks for reporting the issue 😊, the package is completely tested on Android only, I will push a new version after tests complete.

**Comment by Ingenious-App-Studios** [comment]
I am facing the same issue, is there any estimate for when this will be resolved?

**Comment by ayoubamine** [comment]
Done in [v0.0.5](https://pub.dev/packages/flutter_tawk)
